services:
  gateway:
    build:
      context: .
    env_file:
      - .env.local
    depends_on:
      - session-service
      - user-service
      - event-service
    command: ["healthcheck.GatewayApp"]
    environment:
      SESSION_SERVICE_URL: "http://session-service:${SESSION_SERVICE_PORT}"
      USER_SERVICE_URL: "http://user-service:${USER_SERVICE_PORT}"
      EVENT_SERVICE_URL: "http://event-service:${EVENT_SERVICE_PORT}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
  session-service:
    build:
      context: .
    env_file:
      - .env.local
    depends_on:
      - redis
    command: ["healthcheck.SessionServiceApp"]
    expose:
      - "${SESSION_SERVICE_PORT}"
  user-service:
    build:
      context: .
    env_file:
      - .env.local
    depends_on:
      - mongodb
    command: ["healthcheck.UserServiceApp"]
    expose:
      - "${USER_SERVICE_PORT}"
  event-service:
    build:
      context: .
    env_file:
      - .env.local
    depends_on:
      - mongodb
    command: ["healthcheck.EventServiceApp"]
    expose:
      - "${EVENT_SERVICE_PORT}"
  redis:
    image: redis:7.4-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no", "--port", "${REDIS_PORT}"]
    env_file:
      - .env.local
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  mongodb:
    image: mongo:7
    command: [ "mongod", "--bind_ip_all", "--port", "${MONGODB_PORT}" ]
    env_file:
      - .env.local
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGODB_DATABASE}"
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/01-mongo-init.js:ro
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"